# Generated by Django 4.2.6 on 2023-11-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('titulos', models.CharField(max_length=30)),
                ('fundacao', models.CharField(max_length=4)),
            ],
        ),
    ]
